### ISSUE TITLE
numeric literals

### ISSUE THREAD

**Issue by iirftw** [yyyyyyyan/rockstar-py#20]
numeric literals are not supported as in the code

Limit is 100
Counter is 0
Fizz is 3
Buzz is 5

which generates the output

Limit = 0
Counter = 0
Fizz = 0
Buzz = 0

when it should generate the output

Limit = 100
Counter = 0
Fizz = 3
Buzz = 5

**Comment by yanorestes** [comment]
I know the minimalist FizzBuzz example uses this syntax, but I'm not sure it should work. I'll put that on hold and create an issue at Rockstar docs. Thanks for pointing that out, though!
