### ISSUE TITLE
Can't import rockstar-py into other python code

### ISSUE THREAD

**Issue by stretchyboy** [yyyyyyyan/rockstar-py#28]
Currently building some python code that uses rockstar transpiling (I actually have an almost practicable purpose for rockstar :) ).

I tried using the pip install but the "-" in rockstar-py is not valid in a python incude statement.

Copying the rockstar folder in to my project worked fine so, it is not the code, just the packaging that is the problem.

**Comment by yanorestes** [comment]
README specifies `pip install rockstarpy`, without the"-'. That will work

**Comment by stretchyboy** [comment]
Thank you.

But there seems to be some confusion because the - is still there on the master README now. It was those instructions I was following. 

https://github.com/yanorestes/rockstar-py/blob/7525d8377eef341723cec66d4fa547565126ec17/README.rst

**Comment by stretchyboy** [comment]
And this is my result
pip install rockstarpy

Collecting rockstarpy
  Could not find a version that satisfies the requirement rockstarpy (from versions: )
No matching distribution found for rockstarpy

pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by yanorestes** [comment]
Whoopsy, I got a bit confused, sorry. pip install rockstar-py should work perfectly. It is not a valid package name, but it is a valid pip package name. When you install it with pip, you'll have to import using `import rockstarpy`

**Comment by yanorestes** [comment]
Also, Python 2.7 is not strictly supported by rockstar-py. There're probably multiple bugs you'll face, so I recommend using Python >= 3.4

**Comment by stretchyboy** [comment]
Thanks for that. I've upgraded it all to Python 3.6.7

```import rockstarpy``` does not error, but I still can't seem to get hold of the Transpiler. 

```
from rockstarpy.transpile import Transpiler
transpiler = Transpiler()
```
ModuleNotFoundError: No module named 'rockstarpy.transpile'

Any ideas?

**Comment by mfulleratlassian** [comment]
The version on pypi is older code. You can install the latest directly from GitHub "pip install -U git+https://github.com/yanorestes/rockstar-py.git"

Then your code should work.

**Comment by yyyyyyyan** [comment]
The version on PyPI is now updated, it should all br working.
