### ISSUE TITLE
use global keyword to allow assigning to a variable outside of function scope

### ISSUE THREAD

**Issue by sylvainpolletvillard** [yyyyyyyan/rockstar-py#32]
Hello,

From rockstar spec:

> If a variable is defined outside of a function, it is in global scope. Global scope variables are available everywhere below its first initialization. If a variable is defined inside of a function, it is in local scope. Local scope variables are available from their initialization until the end of the function they are defined in.
> 
> While within a function, if you write to a variable that has been defined in global scope, you write to that variable, you do not define a new local variable.

Currently with rockstar-py, we can read global variables but not reassign them from a function scope. For that, we need to add a global declaration: https://docs.python.org/3/reference/simple_stmts.html?highlight=global#the-global-statement

So the compiler has to list all variables declared as global (i.e. `ident == 0`), then add a `global myVar` line in each function body that refers to it.

I wish I could contribute to this but I'm still a beginner in Python. I picked rockstar-py because  the repository looks active and I got good results so far with my rockstar project.

**Comment by yanorestes** [comment]
That's right, thank you! Will fix this asap
