### ISSUE TITLE
transpiler transpiles true, right, yes, ok into true instead of True

### ISSUE THREAD

**Issue by barshopen** [yyyyyyyan/rockstar-py#34]
I tried to build this package myself using this repo, I've wrote the following file:
**rockstar111.rock:**
```
My heart is ok (should be True)
Tommy says True that (intializes tommy to True that)
Shout My heart
Shout Tommy
```
I transpiled the file using the follwoing command: 
`rockstar-py --input rockstar-tut1.rock --stdout`
output:
```
my_heart = true # should be True
Tommy = "True that " # intializes tommy to True that
print(my_heart)
print(Tommy)
```

**Note: using `pip install rocstar-py` instead of this very repo I'm getting the right output.**

**Comment by yyyyyyyan** [comment]
Fixed by 3739948272da04077661ac28c31aa9a84e698345
